### ISSUE TITLE
CSS3PIE

### ISSUE THREAD

**Issue by dan-lobo-axomic** [Schepp/box-sizing-polyfill#19]
I have tried using this solution to provide a fall-back for ie 7 reference box-sizing: borderbox.

The results are interesting. Certainly this works well on some elements , but often still requires further tweaking and does not alter the behavior of select items in ie 7 that do not have an option to add padding and height etc.

My main bug bear is that it does not seem possible to use this with css3pie, or at least not using multiple .htc files/behaviors on one element.. Not sur ebut this may be a limitation of using .htc files rather than this specific library/plugin.

**Comment by Schepp** [comment]
Hey Dan,

sorry for my late answer.

It doesn't surprise me that my polyfill doesn't play well with CSS3Pie. It is not too common that two polyfills applied to the very same element work together. Reason being that both interfere with each other - at the end they are just scripts that concurrently try to manipulate the element. Not good. But even worse with CSS3Pie since that is sort of Pandora's box. CSS3Pie hides the original element and places a VML vector image behind it which mimics the original element, but with rounded corners, drop-shadow and gradients. This means: The thing you see there is no more the thing you applied my border-box-polyfill onto. Thsi explains why it fails to do its work.

**Comment by dan-lobo-axomic** [comment]
Thanks for the explanation.
