### ISSUE TITLE
Add minimized version

### ISSUE THREAD

**Issue by JohnAlbin** [Schepp/box-sizing-polyfill#8]
The script in boxsizing.htc looks to _mostly_ be JavaScript. Couldn't we apply minimization to those parts of the file to improve front-end performance like other JS libraries?

I've never tried this on an IE-specific behavior script, but I don't see why it shouldn't work.

**Comment by KODerFunk** [comment]
+
I'm using Rails, but still I need a minified version, because HTC just a resource that will take IE.

**Comment by Schepp** [comment]
.htc's are indeed mostly JavaScript with just some specialties. So minification should be possible on those parts of the file. But the thing is that since we are not dealing with 100% javascript you cannot easily automate that step.

On top of that the extra work is not justified from my point of view as are not file sizes the biggest performance hit but instead the amount of additional HTTP-requests. Plus you can switch on GZIP compression on your server which nearly annihilates the extra gains imposed by minification. And please believe me that I am all about [web performance optimization](https://github.com/Schepp/CSS-JS-Booster).

**Comment by JohnAlbin** [comment]
Thanks for your thoughts. :-)
